local vscode = require("vscode")
local set = vim.keymap.set

-- Window Actions
set("n", "<leader>wv", function()
	vscode.action("workbench.action.splitEditor")
end)
set("n", "<leader>ws", function()
	vscode.action("workbench.action.splitEditorDown")
end)
set("n", "<leader>wq", function()
	vscode.action("workbench.action.closeEditorsAndGroup")
end)
set("n", "<C-h>", function()
	vscode.action("workbench.action.focusLeftGroup")
end)
set("n", "<C-j>", function()
	vscode.action("workbench.action.focusBelowGroup")
end)
set("n", "<C-k>", function()
	vscode.action("workbench.action.focusAboveGroup")
end)
set("n", "<C-l>", function()
	vscode.action("workbench.action.focusRightGroup")
end)

-- Project Actions
set("n", "<leader>pf", function()
	vscode.action("workbench.action.quickOpen")
end)
set("n", "<leader>ps", function()
	vscode.action("workbench.action.showAllSymbols")
end)
set("n", "<leader>/", function()
	vscode.action("search.action.openEditor")
end)

-- Buffer Actions
set("n", "<leader>bb", function()
	vscode.action("workbench.action.showEditorsInActiveGroup")
end)
set("n", "<leader>bd", function()
	vscode.action("workbench.action.closeActiveEditor")
end)

-- File Actions
set("n", "<leader>fs", function()
	vscode.action("workbench.action.gotoSymbol")
end)
set("n", "<leader>fn", function()
	vscode.action("fileutils.newFile")
end)
set("n", "<leader>fN", function()
	vscode.action("fileutils.newFileAtRoot")
end)
set("n", "<leader>fd", function()
	vscode.action("fileutils.newFolder")
end)
set("n", "<leader>fD", function()
	vscode.action("fileutils.newFolderAtRoot")
end)
set("n", "<leader>fx", function()
	vscode.action("fileutils.removeFile")
end)
set("n", "<leader>fm", function()
	vscode.action("fileutils.moveFile")
end)
set("n", "<leader>fr", function()
	vscode.action("fileutils.renameFile")
end)
set("n", "<leader>fj", function()
	vscode.action("workbench.action.openSettingsJson")
end)
set("n", "<leader>fk", function()
	vscode.action("workbench.action.openGlobalKeybindingsFile")
end)

-- Code Actions
set("n", "<leader>ca", function()
	vscode.action("editor.action.quickFix")
end)
set("n", "<leader>cr", function()
	vscode.action("editor.action.rename")
end)
set("v", "<leader>cb", function()
	vscode.action("editor.action.blockComment")
end)

-- Toggle Actions
set("n", "<leader>ts", function()
	vscode.action("workbench.action.toggleSidebarVisibility")
end)
set("n", "<leader>te", function()
	vscode.action("workbench.view.explorer")
	vscode.action("workbench.action.focusActiveEditorGroup")
end)

-- Misc Actions
set("n", "<leader>gp", function()
	vscode.action("editor.action.revealDefinitionAside")
end)
set("n", "K", function()
	vscode.action("editor.action.showHover")
end)
set("n", "<C-n>", function()
	vim.cmd("let @/ = ''")
	vim.cmd("nohlsearch")
end)
set("v", "p", "P")
set("v", "<", "<gv")
set("v", ">", ">gv")
set("n", ">", ">>")
set("n", "<", "<<")
set("v", "J", function()
	vim.cmd("m '<+1<CR>gv=gv")
end)
set("v", "K", function()
	vim.cmd("m '<-2<CR>gv=gv")
end)
set("v", "<leader>y", '"+y')
set("n", "J", vim.diagnostic.open_float)
