local vscode = require("vscode")
vim.opt.cursorline = false
vim.showmode = true
vim.opt.incsearch = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.backup = false
vim.opt.scrolloff = 8
vim.o.laststatus = 2
vim.opt.guicursor = "n-v-c-i:block"
vim.opt.autoindent = true
vim.opt.cindent = true
vim.g.clipboard = vim.g.vscode_clipboard
vim.notify = vscode.notify

-- Editor Config
vscode.update_config("editor.lineNumbers", "relative", "global")
vscode.update_config("editor.codeActionWidget.showHeaders", false, "global")
vscode.update_config("editor.hover.above", false, "global")
vscode.update_config("editor.scrollbar.horizontal", "hidden", "global")
vscode.update_config("editor.insertSpaces", false, "global")
vscode.update_config("editor.inlayHints.enabled", "off", "global")
vscode.update_config("editor.lineHeight", 1.15, "global")
vscode.update_config("editor.cursorBlinking", "solid", "global")
vscode.update_config("editor.hover.enabled", "off", "global")
vscode.update_config("editor.codeLens", false, "global")
vscode.update_config("editor.bracketPairColorization.enabled", false, "global")
vscode.update_config("editor.stickyScroll.enabled", false, "global")
vscode.update_config("editor.minimap.enabled", false, "global")
vscode.update_config("editor.fontSize", 13, "global")
vscode.update_config("editor.peekWidgetDefaultFocus", "tree", "global")
vscode.update_config("editor.renderLineHighlight", "none", "global")
vscode.update_config("editor.guides.bracketPairs", false, "global")
vscode.update_config("editor.guides.bracketPairsHorizontal", false, "global")
vscode.update_config("editor.selectionHighlight", false, "global")
vscode.update_config("editor.occurrencesHighlight", "off", "global")
vscode.update_config("editor.guides.indentation", false, "global")
vscode.update_config("editor.wordWrap", "on", "global")
-- Workbench Config
vscode.update_config("workbench.editor.useModal", "off", "global")
vscode.update_config("workbench.navigationControl.enabled", false, "global")
vscode.update_config("workbench.startupEditor", "none", "global")
vscode.update_config("workbench.editor.enablePreview", false, "global")
vscode.update_config("workbench.editor.showTabs", "none", "global")
vscode.update_config("workbench.editor.editorActionsLocation", "hidden", "global")
vscode.update_config("workbench.activityBar.location", "hidden", "global")
vscode.update_config("workbench.panel.showLabels", false, "global")
vscode.update_config("workbench.layoutControl.enabled", false, "global")
vscode.update_config("workbench.notifications.position", "top-right", "global")
vscode.update_config("workbench.editor.titleScrollbarVisibility", "hidden", "global")
vscode.update_config("workbench.activityBar.autoHide", true, "global")
vscode.update_config("workbench.secondarySideBar.defaultVisibility", "hidden", "global")
vscode.update_config("workbench.browser.showInTitleBar", false, "global")
vscode.update_config("workbench.colorTheme", "Kanagawa", "global")
vscode.update_config("workbench.iconTheme", "material-icon-theme", "global")
-- Window Config
vscode.update_config("window.menuBarVisibility", "compact", "global")
vscode.update_config("window.titleBarStyle", "custom", "global")
vscode.update_config("window.title", "${activeFolderMedium}${separator}${activeEditorShort}${separator}${activeRepositoryBranchName} ${dirty}", "global")
vscode.update_config("window.commandCenter", false, "global")
-- Terminal Config
vscode.update_config("terminal.integrated.allowChords", false, "global")
vscode.update_config("terminal.integrated.hideOnStartup", "always", "global")
vscode.update_config("terminal.integrated.defaultLocation", "editor", "global")
vscode.update_config("terminal.integrated.scrollback", 5000, "global")
vscode.update_config("terminal.integrated.stickyScroll.enabled", false, "global")
vscode.update_config("terminal.integrated.suggest.enabled", false, "global")
-- Search Config
vscode.update_config("search.showLineNumbers", true, "global")
vscode.update_config("search.smartCase", true, "global")
vscode.update_config("search.searchEditor.defaultNumberOfContextLines", 0, "global")
vscode.update_config("search.searchEditor.focusResultsOnSearch", false, "global")
vscode.update_config("search.quickOpen.includeHistory", false, "global")
vscode.update_config("search.quickOpen.history.filterSortOrder", "recency", "global")
-- Error Lens Config
vscode.update_config("errorLens.fontWeight", "bold", "global")
vscode.update_config("errorLens.fontStyleItalic", true, "global")
vscode.update_config("errorLens.messageBackgroundMode", "none", "global")
-- Breadcrumbs Config
vscode.update_config("breadcrumbs.enabled", false, "global")
-- Languages Config
vscode.update_config("python.analysis.typeCheckingMode", "standard", "global")
vscode.update_config("powershell.integratedConsole.startInBackground", true, "global")
-- Misc Config
vscode.update_config("chat.titleBar.signIn.enabled", false, "global")