vim.keymap.set("v", "<leader>y", '"+y')
vim.keymap.set("n", "<leader>up", vim.cmd.UpdatePlugins)
vim.keymap.set("n", "<leader>cp", vim.cmd.CleanPlugins)
vim.keymap.set("n", "<leader>bd", vim.cmd.CloseBuffer)
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action)
vim.keymap.set("n", "<leader>cr", vim.lsp.buf.rename)
vim.keymap.set("n", "<leader>cf", vim.lsp.buf.format)
vim.keymap.set("n", "<leader>cl", function() vim.cmd.checkhealth("vim.lsp") end)
vim.keymap.set("n", "<leader>qq", vim.cmd.Ex)
vim.keymap.set("n", "<leader>ws", vim.cmd.split)
vim.keymap.set("n", "<leader>wv", vim.cmd.vsplit)
vim.keymap.set("n", "<leader>wq", vim.cmd.close)
vim.keymap.set("n", "gd", vim.lsp.buf.definition)
vim.keymap.set("n", "gr", vim.lsp.buf.references)
vim.keymap.set("n", "gi", vim.lsp.buf.implementation)
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("n", "<", "<<")
vim.keymap.set("n", ">", ">>")
vim.keymap.set("v", "p", "P")
vim.keymap.set("n", "<C-n>", vim.cmd.nohlsearch)
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "K", vim.lsp.buf.hover)
vim.keymap.set("n", "J", vim.diagnostic.open_float)
vim.keymap.set("n", "<leader>tn", vim.cmd.terminal)
vim.keymap.set("t", "<Esc>", [[<C-\><C-n>]])
vim.keymap.set("t", "<C-x>", vim.cmd.CloseBuffer)
vim.keymap.set("t", "<C-t>", vim.cmd.OpenPreviousBuffer)
if vim.g.neovide then
    vim.keymap.set("n", "<C-h>", function()
        vim.cmd.wincmd("h")
    end)
    vim.keymap.set("n", "<C-j>", function()
        vim.cmd.wincmd("j")
    end)
    vim.keymap.set("n", "<C-k>", function()
        vim.cmd.wincmd("k")
    end)
    vim.keymap.set("n", "<C-l>", function()
        vim.cmd.wincmd("l")
    end)
    vim.keymap.set("t", "<C-h>", function()
        vim.cmd.wincmd("h")
    end)
    vim.keymap.set("t", "<C-j>", function()
        vim.cmd.wincmd("j")
    end)
    vim.keymap.set("t", "<C-k>", function()
        vim.cmd.wincmd("k")
    end)
    vim.keymap.set("t", "<C-l>", function()
        vim.cmd.wincmd("l")
    end)
end
