local set = vim.keymap.set
local pick_funcs = require("core.pick_functions")

-- Misc Leader Actions
set("n", "<leader>/", function()
	vim.cmd.Pick("grep_live")
end)
-- set("n", "<leader>?", function()
-- 	vim.cmd.Telescope("keymaps")
-- end)
set("n", "<leader>ht", function()
	vim.cmd.Pick("help")
end)
set({"v", "n"}, "<leader>y", '"+y')
set("n", "<leader>m", function()
	vim.cmd.Telescope("man_pages")
end)
-- set("n", "<leader>a", function()
-- 	vim.cmd.Telescope("autocommands")
-- end)
-- Buffer Actions
set("n", "<leader>bb", function()
	vim.cmd.Pick("buffers")
end)
set("n", "<leader>bd", vim.cmd.CloseBuffer)
-- Code / Compile Actions
set("n", "<leader>ca", vim.lsp.buf.code_action)
-- set("n", "<leader>cs", function()
-- 	vim.cmd.Telescope("treesitter")
-- end)
set("n", "<leader>cr", vim.lsp.buf.rename)
-- set("n", "<leader>ch", function()
-- 	vim.cmd.Telescope("command_history")
-- end)
set("n", "<leader>cc", function()
	vim.cmd.ReadCmd()
end)
set("n", "<leader>cf", vim.lsp.buf.format)
set("n", "<leader>cl", function()
	vim.cmd.checkhealth("lsp")
end)
set("n", "<leader>ct", vim.cmd.TSInstalled)
-- File Actions
set("n", "<leader>ff", function()
	vim.cmd.Pick("files")
end)
-- Git Actions
set("n", "<leader>gb", function()
	local branch = vim.fn.input("Branch name: ")
	if branch ~= "" then
		vim.cmd.Git("checkout -b " .. branch)
		vim.cmd.Git("push -u origin " .. branch)
	end
end)
set("n", "<leader>gg", vim.cmd.Git)
set("n", "<leader>gD", vim.cmd.Gdiffsplit)
set("n", "<leader>gC", vim.cmd.CreateBranch)
set("n", "<leader>gA", function()
	vim.cmd.Git("add --all")
end)
set("n", "<leader>ga", function ()
    pick_funcs.git_add()
end)
set("n", "<leader>gc", function()
	vim.cmd.Git("commit")
end)
set("n", "<leader>gp", function()
	vim.cmd.Git("push")
end)
set("n", "<leader>gP", function()
	vim.cmd.Git("pull --rebase")
end)
set("n", "<leader>gB", function()
	vim.cmd.Git("blame")
end)
set("n", "<leader>gM", function()
	vim.cmd.Git("mergetool")
end)
set("n", "<leader>gd", function()
	vim.cmd.Git("diff")
end)
set("n", "<leader>gl", function()
	vim.cmd.Git("log")
end)
set("n", "<leader>gu", function ()
    pick_funcs.git_unstage()
end)
set("n", "<leader>gU", function()
	vim.cmd.Git("restore --staged :/")
end)
set("n", "<leader>gr", function ()
    pick_funcs.git_restore()
end)
set("n", "<leader>gR", function ()
	local confirm = vim.fn.input("Do you want to restore ALL files(yes/no): ")
	if confirm == "yes" then
		vim.cmd.Git("restore :/")
	end
end)
set("n", "<leader>ge", function ()
    pick_funcs.git_rebase()
end)
set("n", "<leader>gF", function()
	vim.cmd.Git("fetch")
end)
set("n", "<leader>gj", function()
	vim.cmd("diffget //2<CR>")
end)
set("n", "<leader>gf", function()
	vim.cmd("diffget //3<CR>")
end)
set("n", "<leader>go", vim.cmd.PrintConflicts)
set("n", "<leader>gss", function ()
    pick_funcs.git_stash()
end)
set("n", "<leader>gsS", function ()
    vim.cmd.Git("stash")
end)
set("n", "<leader>gsl", function()
	pick_funcs.git_stash_list()
end)
set("n", "<leader>gsc", function()
	vim.cmd.Git("stash clear")
end)
set("n", "<leader>gmu", function ()
    pick_funcs.git_update_submodules()
end)
-- Toggle Actions
set("n", "<leader>tu", vim.cmd.UndotreeToggle)
-- Project Actions
set("n", "<leader>pf", function ()
    pick_funcs.git_files()
end)
-- set("n", "<leader>pD", function()
-- 	vim.cmd.Telescope("diagnostics")
-- end)
set("n", "<leader>qq", vim.cmd.Ex)
-- Window Actions
set("n", "<leader>ws", vim.cmd.split)
set("n", "<leader>wv", vim.cmd.vsplit)
set("n", "<leader>wq", vim.cmd.close)
-- Misc Actions
set("n", "gd", function()
	vim.lsp.buf.definition({})
end)
set("n", "gr", function()
    vim.lsp.buf.references()
end)
set("n", "gi", function()
    vim.lsp.buf.implementation()
end)
set("v", "<", "<gv")
set("v", ">", ">gv")
set("n", "<", "<<")
set("n", ">", ">>")
set("v", "p", "_dP")
set("n", "<C-n>", function()
	vim.cmd("nohlsearch")
end)
set("v", "J", ":m '>+1<CR>gv=gv")
set("v", "K", ":m '<-2<CR>gv=gv")
set("n", "K", vim.lsp.buf.hover)
set("n", "J", vim.diagnostic.open_float)
