require("lazy_load").on_vim_enter(function()
    vim.pack.add({
        GIT_ROOT .. "tpope/vim-fugitive"
    })

    vim.keymap.set("n", "<leader>gg", function ()
        vim.cmd.Git()
        vim.cmd.only()
    end)
    vim.keymap.set("n", "<leader>gw", function()
        vim.cmd.Git("blame")
    end)
    vim.keymap.set("n", "<leader>gl", function ()
        vim.cmd.Git("--paginate log")
    end)
    vim.keymap.set("n", "<leader>gd", function ()
        vim.cmd.Git("--paginate diff")
    end)
    vim.keymap.set("n", "<leader>gm", function ()
        vim.cmd.Git("mergetool")
    end)
    vim.keymap.set("n", "<leader>gt", function ()
        vim.cmd.Git("difftool")
    end)
end)
