if false then
    require("lazy_load").on_vim_enter(function()
        vim.pack.add({
            { src = GIT_ROOT .. "sindrets/diffview.nvim" },
            { src = GIT_ROOT .. "NeogitOrg/neogit" }
        })

        local neogit = require("neogit")
        neogit.setup({})
        vim.keymap.set("n", "<leader>gg", neogit.open)
        vim.keymap.set("n", "<leader>gb", function()
            neogit.open({ "branch" })
        end)
        vim.keymap.set("n", "<leader>gd", function()
            neogit.open({ "diff" })
        end)
        vim.keymap.set("n", "<leader>gc", function()
            neogit.open({ "commit" })
        end)
        vim.keymap.set("n", "<leader>gi", function()
            neogit.open({ "ignore" })
        end)
        vim.keymap.set("n", "<leader>gl", function()
            neogit.open({ "log" })
        end)
        vim.keymap.set("n", "<leader>gp", function()
            neogit.open({ "pull" })
        end)
        vim.keymap.set("n", "<leader>gP", function()
            neogit.open({ "push" })
        end)
        vim.keymap.set("n", "<leader>gs", function()
            neogit.open({ "stash" })
        end)
    end)
end
